name: ShoppyX
version: '1.0-SNAPSHOT'
main: kr.doka.lab.shoppy.paper.ShoppyPlugin
api-version: '1.21'
authors: [ DOKA1203 ]
bootstrapper: kr.doka.lab.shoppy.paper.ShoppyPluginBootstrapper
loader: kr.doka.lab.shoppy.paper.ShoppyPluginLoader
